# system configuration
system:
  env: "develop" # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: "postgres"
  static-path: uploads/file
  web-url: "http://127.0.0.1:3100"

# zap logger configuration
zap:
  level: "info"
  format: "console"
  prefix: "[<%= displayName %>]"
  director: "log"
  link-name: "latest_log"
  show-line: true
  encode-level: "LowercaseColorLevelEncoder"
  stacktrace-key: "stacktrace"
  log-in-console: true

# jwt configuration
jwt:
  signing-key: "<%= displayName %>"
  expires-time: 604800
  buffer-time: 86400

postgres:
  host: localhost
  port: 5432
  db-name: database
  username: postgres
  password: hello123
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: true
  log-zap: warn

redis:
  host: localhost:6379

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'