version: "3.5"

services:
  pgsql:
    image: postgres:latest
    container_name: pgsql
    restart: always
    ports:
      - "0.0.0.0:5439:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello123
      - TZ=Asia/Shanghai

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "0.0.0.0:6379:6379"
    command: redis-server /usr/local/etc/redis/redis.conf

  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "8899:8888"
    restart: always
    volumes:
      - ../config.prd.yaml:/usr/src/app/config.prd.yaml
    command: ["./server"]
    depends_on:
      - pgsql
      - redis
    environment:
      - <%= displayName %>_CONFIG=./config.prd.yaml
