package source

var Casbin_rules = [][]string{
	{"444", "/menu/getMenuByUser", "POST"},
	{"555", "/menu/getMenuList", "GET"},
	{"555", "/menu/addMenu", "POST", "SystemMenu:create"},
	{"555", "/menu/deleteMenu", "DELETE", "SystemMenu:delete"},
	{"555", "/menu/updateMenu", "POST", "SystemMenu:edit|SystemMenu:create_child"},
	{"444", "/menu/getMenuById", "GET"},
	{"555", "/menu/getMenuByRole", "GET"},
	{"555", "/menu/addRoleMenu", "POST", "UserRole:menu"},
	{"777", "/menu/deleteButton", "POST"},
	{"777", "/menu/updateButton", "POST"},
	{"777", "/menu/addButton", "POST"},
	{"444", "/menu/getButtonByUser", "GET"},
	{"444", "/user/detail/*", "GET"},
	{"444", "/user/update", "POST", "UserList:edit"},
	{"444", "/user/list", "GET"},
	{"444", "/user/callback", "POST"},
	{"444", "/user/userInfo", "GET"},
	{"555", "/user/*", "DELETE"},
	{"444", "/user/searchLDAP", "GET"},
	{"444", "/user/password", "POST", "UserMe:edit_password"},
	{"444", "/user/userInfo/update", "POST"},
	{"555", "/role/list", "GET"},
	{"555", "/role/detail/*", "GET"},
	{"777", "/role/create", "POST", "UserRole:create"},
	{"777", "/role/update", "POST", "UserRole:edit"},
	{"777", "/role/*", "DELETE", "UserRole:delete"},
	{"555", "/role/user/list", "GET"},
	{"777", "/roleuser/add", "POST", "UserList:add_role_user"},
	{"777", "/roleuser/*", "DELETE", "UserList:delete_role_user"},
	{"777", "/casbin/list", "GET"},
	{"777", "/casbin/update", "POST"},
	{"444", "/dashboard/info", "GET"},
	{"555", "/system/getServerInfo", "GET"},
	{"555", "/system/getSystemConfig", "GET"},
	{"777", "/casbin/updateById", "POST", "SystemCasbin:auth|SystemCasbin:method|SystemCasbin:button"},
}
